pg_virtualenv: Error out if no server packages are installed.

diff --git a/pg_virtualenv b/pg_virtualenv
--- a/pg_virtualenv
+++ b/pg_virtualenv
@@ -78,7 +78,11 @@ while getopts "ac:i:ho:stv:" opt ; do
 done
 if [ -z "$PG_VERSIONS" ]; then
     # use latest version
-    d=$(ls -v $PGBINROOT*/bin/pg_ctl | tail -1)
+    d=$(ls -v $PGBINROOT*/bin/pg_ctl 2> /dev/null | tail -1)
+    if [ -z "$d" ]; then
+        echo "Could not determine PostgreSQL version, are any PostgreSQL server packages installed?" >&2
+        exit 2
+    fi
     dir=${d%%/bin/pg_ctl}
     PG_VERSIONS="${dir#$PGBINROOT}"
 fi
