* debian/maintscripts-functions: Do not fail package installation if   pg_createcluster fails (/var might be full and the admin might want to use   a different directory). Merely print out an error message and point to   pg_createcluster and its manpage. (part of bug #368335)

diff --git a/postgresql-common/debian/maintscripts-functions b/postgresql-common/debian/maintscripts-functions
--- a/postgresql-common/debian/maintscripts-functions
+++ b/postgresql-common/debian/maintscripts-functions
@@ -23,7 +23,13 @@ configure_version() {
     [ "$VERSION" ] || { echo "Error: configure_version: need version parameter" >&2; exit 1; }
     if [ ! -d "/etc/postgresql/$VERSION" ] || [ -z "$(ls /etc/postgresql/$VERSION)" ] || \
        [ -z "$(ls /etc/postgresql/$VERSION/*/postgresql.conf 2>/dev/null)" ]; then
-        [ "$2" ] || /usr/bin/pg_createcluster -u postgres $VERSION main
+        [ "$2" ] || /usr/bin/pg_createcluster -u postgres $VERSION main || {
+	echo "Error: could not create default cluster. Please create it manually with
+
+  pg_createcluster $VERSION main --start
+
+or a similar command (see 'man pg_createcluster')." >&2
+	}
     fi
 
     _link_manpages "$VERSION" "postgresql-$VERSION" postmaster.1.gz
