Add debconf note about obsolete versions

diff --git a/postgresql-common/debian/postgresql-common.postinst b/postgresql-common/debian/postgresql-common.postinst
--- a/postgresql-common/debian/postgresql-common.postinst
+++ b/postgresql-common/debian/postgresql-common.postinst
@@ -1,4 +1,6 @@
 #!/bin/sh
+. /usr/share/debconf/confmodule
+db_stop
 
 SSL_CERT=/etc/postgresql-common/postgresql.crt
 SSL_KEY=/etc/postgresql-common/postgresql.pem
@@ -26,7 +28,7 @@ EOF
         chmod 0644 $SSL_CERT
 	chown postgres:postgres $SSL_KEY
         chmod 0600 $SSL_KEY
-        ) || echo "Warning : Bad SSL config, can't generate certificate"
+        ) || echo "Warning : Bad SSL config, can't generate certificate" >&2
     fi
 }
 
